USE [Exams]

ALTER TABLE Students
	DROP CONSTRAINT FK__Students__Group___30F848ED; --check exact name in the DB

ALTER TABLE Students
	ADD FOREIGN KEY (Group_Id) REFERENCES Groups(Gr_Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

ALTER TABLE Marks
	ADD FOREIGN KEY (Student_Id) REFERENCES Students(Stud_Id)
	ON DELETE CASCADE;

ALTER TABLE Marks
	ADD FOREIGN KEY (Teacher_Id) REFERENCES Teachers(Teacher_Id)
	ON DELETE CASCADE;

ALTER TABLE Marks
	ADD FOREIGN KEY (Disc_Id) REFERENCES Disciplines(Discipline_Id)
	ON DELETE CASCADE;