ALTER TABLE Students
	CHECK CONSTRAINT FK__Students__Group___31EC6D26;

ALTER TABLE Marks
	CHECK CONSTRAINT FK__Students__Group___31EC6D26;

ALTER TABLE Marks
	CHECK CONSTRAINT FK__Students__Group___31EC6D26;

ALTER TABLE Marks
	CHECK CONSTRAINT FK__Students__Group___31EC6D26;